### ISSUE TITLE
Allow integrating Blueprinter with AMS

### ISSUE THREAD

**Issue by HParker** [procore/blueprinter#167]
I am looking to introduce Blueprinter into a codebase that already uses AMS. Would you be open to adding a feature on `field` that allowed you to specify a `active_model_serializer:` instead of a `blueprint:` like today? That way even with very interrelated serializers you would be able to start migrating to blueprinter without having to migrate a whole object graph.

cc @philipqnguyen @dlcarter

**Comment by AllPurposeName** [comment]
This is a good idea. Wholesale switchover to Blueprinter is infeasible otherwise.

**Comment by pjmartorell** [comment]
This probably would incentive that people missuse the gem, having mixed serializers forever, raising unexpected errors, opening more issues here and having to maintain compatibility with this feature in the next versions. If you want to add a custom functionality for your particular case maybe it would be better that you fork or monkey-patch blueprint instead of making blueprint to integrate with other gems.

**Comment by HParker** [comment]
Totally fair, the PR discussion came to the same conclusion. 👍
