### ISSUE TITLE
rename association key

### ISSUE THREAD

**Issue by krtschmr** [procore/blueprinter#270]
i would have expected to be able to rename the association key, but i didn't had success. i checked the code and dint' find ability. i would suggest a keyword `as:` would be useful

```
class ABlueprint < Blueprinter::Base
  identifier :id
  fields :name, :position, :updated_at
  association :somethings, blueprint: Blueprint, as: "something_else"
end

```

**Comment by mcclayton** [comment]
This is possible via directly defining the association using a block like:
```rb
class ABlueprint < Blueprinter::Base
  identifier :id
  fields :name, :position, :updated_at
  association :something_else, blueprint: Blueprint do |object, options|
    object.somthings
  end
end
```

**Comment by krtschmr** [comment]
Yes, i figured out that workaround, i just wonder if the `as` makes sense as it fits nice into the DSL and keep things tidy.

**Comment by mcclayton** [comment]
Glad you figured it out. 
There have been a few proposed mechanisms for aliasing fields and/or for delegation. However, since all these proposals have been encapsulated by the method above, we've opted not to introduce more extraneous syntax here.

We can certainly make the docs clearer on this though. Closing the issue, but please let us know if you have any other issues!

**Comment by Tao-Galasse** [comment]
@mcclayton Hello!

I just ran into the issue today and it doesn't seem to work for me. If I write something like this :
```
association :something_else, blueprint: MyModelBlueprint do |object, options|
    object.somethings
  end
```
I get this error : 
`ActiveRecord::AssociationNotFoundError: Association named 'something_else' was not found on MyModel; perhaps you misspelled it?`

any idea what could possibly go wrong here?
