### ISSUE TITLE
Idea : provide a mapper

### ISSUE THREAD

**Issue by Systho** [procore/blueprinter#92]
I've had a little time to work on my problem described in #90 and I made a better solution (at leats to my eyes )

Here is the code of my patch (which I execute at the start of my app)

```ruby
module BlueprintDelegation

  def mapping(&block)
    delegator_class.class_eval(&block)
  end

  #below this is private API

  # this is the tricky part, this method must store a different delegator class in each blueprint
  def delegator_class
    @delegator_class ||= Class.new(SimpleDelegator)
  end

  def build_object_delegator(object)
    delegator_class.new(object)
  end
  
  def object_to_hash(object, **named_params)
    object_delegator = build_object_delegator(object)
    super(object_delegator, **named_params)
  end
  
end

Blueprinter::Base.singleton_class.prepend BlueprintDelegation

```

The usage is done like this :

```ruby
module PublicApi
  module V1
    class UserBlueprint < BaseBlueprint

      field :first_name
      field :last_name
      field :email

      view(:show) do
        association(:participations, blueprint: ParticipationBlueprint)
      end

      mapping do
        def participations
          learner.participations
        end
      end

    end
  end
end
```

I feel this is prettier than passing blocks all over the place and is usable with fields and associations and any extractor .

If you like the idea I'll make a PR

**Comment by philipqnguyen** [comment]
@Systho I like the idea because this would suddenly allow `fields` and `associations` the ability to customize, but this also does what `field` blocks already does.

If we introduce `mapping`, should we continue supporting `field` blocks or should it be deprecated? For me, I don't like the idea of officially supporting both `field` blocks and `mapping` side by side because it can be confusing for people to know when to use which.

In addition, `field` blocks supports additional properties option https://github.com/procore/blueprinter#passing-additional-properties-to-render
Should `mapping` handle that too?

@dlcarter do you want to chime in?

**Comment by Systho** [comment]
I think the `mapping` idea is better than the block because : 
 - it enables fields and associations to have mapping without duplicating code.
 - Since it's usual OO, we can use the usual design tools to improve it. Blocks have fewer improvement possibilities.

I think you can either deprecate blocks, or have the provided block define a method in the delegator_class :) 

I can make `options` available in the mapping methods as a readable_attribute of the delegator_class.

**Comment by philipqnguyen** [comment]
I think `mapping` is great, but due to the previous decision of going with field blocks, I'm hesitant to introduce `mapping`. `mapping` would greatly change blueprinter's public API. I think it's important to support one over the other to reduce confusion, so if we were to introduce mapping, then field blocks would deprecate, which would lead to breaking changes to many projects.

**Comment by philipqnguyen** [comment]
closing for now.
